services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    env_file: ./.env
    command: ["make", "startDev"]
